const loginlanguage = {
  English: {
    loginsignInbtn: "Sign In",
    loginsignupbtn: "Sign Up",
    nameplaceholder: "Name",
    emailplaceholder: "Email",
    passwordplaceholder: "password",
    signInupnowpara: "New to Netflix? Sign up now.",
    signInnowpara: "Already have an account? Sign in now.",
    signuperror: "User Already exist.",
    signinerror: "User Not Found.",
  },
  Hindi: {
    loginsignInbtn: "साइन इन",
    loginsignupbtn: "साइन अप",
    nameplaceholder: "नाम",
    emailplaceholder: "ईमेल",
    passwordplaceholder: "पासवर्ड",
    signInupnowpara: "Netflix पर नए हैं? अभी साइन अप करें।",
    signInnowpara: "पहले से खाता है? अभी साइन इन करें।",
    signuperror: "उपयोगकर्ता पहले से मौजूद है।",
    signinerror: "उपयोगकर्ता नहीं मिला।",
  },
  Urdu: {
    loginsignInbtn: "سائن اِن",
    loginsignupbtn: "سائن اَپ",
    nameplaceholder: "نام",
    emailplaceholder: "ای میل",
    passwordplaceholder: "پاس ورڈ",
    signInupnowpara: "نیٹ فلکس پر نئے ہیں؟ ابھی سائن اَپ کریں۔",
    signInnowpara: "پہلے سے اکاؤنٹ ہے؟ ابھی سائن اِن کریں۔",
    signuperror: "صارف پہلے سے موجود ہے۔",
    signinerror: "صارف نہیں ملا۔",
  },
  Turkish: {
    loginsignInbtn: "Giriş Yap",
    loginsignupbtn: "Kayıt Ol",
    nameplaceholder: "Ad",
    emailplaceholder: "E-posta",
    passwordplaceholder: "Şifre",
    signInupnowpara: "Netflix'e yeni misiniz? Hemen kaydolun.",
    signInnowpara: "Zaten bir hesabınız var mı? Hemen giriş yapın.",
    signuperror: "Kullanıcı zaten mevcut.",
    signinerror: "Kullanıcı bulunamadı.",
  },
  Spanish: {
    loginsignInbtn: "Iniciar sesión",
    loginsignupbtn: "Registrarse",
    nameplaceholder: "Nombre",
    emailplaceholder: "Correo electrónico",
    passwordplaceholder: "Contraseña",
    signInupnowpara: "¿Nuevo en Netflix? Regístrate ahora.",
    signInnowpara: "¿Ya tienes una cuenta? Inicia sesión ahora.",
    signuperror: "El usuario ya existe.",
    signinerror: "Usuario no encontrado.",
  },
  Portuguese: {
    loginsignInbtn: "Entrar",
    loginsignupbtn: "Cadastrar-se",
    nameplaceholder: "Nome",
    emailplaceholder: "E-mail",
    passwordplaceholder: "Senha",
    signInupnowpara: "Novo na Netflix? Cadastre-se agora.",
    signInnowpara: "Já tem uma conta? Entre agora.",
    signuperror: "O usuário já existe.",
    signinerror: "Usuário não encontrado.",
  },
};
export default loginlanguage;
