const Netflixmainlanguage = {
  English: {
    movielist1: "Now playing",
    movielist2: "Toprated",
    movielist3: "Upcoming",
    movielist4: "Popular",
    profile: "Manage Profiles",
    list: "My List",
    Notification: "Notifications",
    Account: "Account",
    signoutbtn: "Sign Out",
    playbtn: "Play",
    moreinfo: "More Info",
    Searchgptbtn:"GPT",
    Searchhomebtn:"Home"
  },
  Hindi: {
    movielist1: "अभी चल रही फ़िल्में",
    movielist2: "सर्वश्रेष्ठ रेटेड",
    movielist3: "आने वाली फ़िल्में",
    movielist4: "लोकप्रिय",
    profile: "प्रोफ़ाइल प्रबंधित करें",
    list: "मेरी सूची",
    Notification: "सूचनाएँ",
    Account: "खाता",
    signoutbtn: "साइन आउट",
    playbtn: "चलाएँ",
    moreinfo: "और जानकारी",
  },

  Urdu: {
    movielist1: "ابھی چل رہی فلمیں",
    movielist2: "اعلیٰ درجہ بندی والی",
    movielist3: "جلد آنے والی فلمیں",
    movielist4: "مقبول",
    profile: "پروفائل کا انتظام کریں",
    list: "میری فہرست",
    Notification: "اطلاعات",
    Account: "اکاؤنٹ",
    signoutbtn: "سائن آؤٹ",
    playbtn: "چلائیں",
    moreinfo: "مزید معلومات",
  },

  Turkish: {
    movielist1: "Şu Anda Gösterimde",
    movielist2: "En Yüksek Puanlı",
    movielist3: "Yakında",
    movielist4: "Popüler",
    profile: "Profilleri Yönet",
    list: "Listem",
    Notification: "Bildirimler",
    Account: "Hesap",
    signoutbtn: "Çıkış Yap",
    playbtn: "Oynat",
    moreinfo: "Daha Fazla Bilgi",
  },

  Spanish: {
    movielist1: "En cartelera",
    movielist2: "Mejor valoradas",
    movielist3: "Próximamente",
    movielist4: "Populares",
    profile: "Administrar perfiles",
    list: "Mi lista",
    Notification: "Notificaciones",
    Account: "Cuenta",
    playbtn: "Reproducir",
    moreinfo: "Más información",
    signoutbtn: "Cerrar sesión",
  },

  Portuguese: {
    movielist1: "Em cartaz",
    movielist2: "Mais bem avaliados",
    movielist3: "Em breve",
    movielist4: "Populares",
    profile: "Gerenciar perfis",
    list: "Minha lista",
    Notification: "Notificações",
    Account: "Conta",
    signoutbtn: "Sair",
    playbtn: "Reproduzir",
    moreinfo: "Mais informações",
  },
};
export default Netflixmainlanguage;
